name: Laravel CI

on:
  push:
    branches:
      - main
      - refactor-architecture
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql, intl, xml, ctype, json
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run Laravel Tests
        run: php artisan test

      - name: Check PHP Syntax (optional)
        run: find app -name "*.php" -exec php -l {} \;
